[package]
name = "zip-password-finder"
version = "0.4.0"
authors = ["Arnaud Gourlay <arnaud.gourlay@gmail.com>"]
description = "Zip archive password finder"
edition = "2021"

[dependencies]
zip = "0.6.3"
crossbeam-channel = "0.5.6"
clap = { version = "4.0.32", features = ["cargo"] }
indicatif = "0.17.2"
thiserror = "1.0.38"
num_cpus = "1.15.0"

[profile.test]
opt-level = 3 # needed for fast execution
