[package]
name = "zip-password-finder"
version = "0.7.0"
description = "Find the password of protected ZIP files"
authors = ["Arnaud Gourlay <arnaud.gourlay@gmail.com>"]
license = "Apache-2.0"
readme = "README.md"
categories = ["command-line-utilities", "command-line-interface", "zip", "archive", "password"]
edition = "2021"

[dependencies]
zip = { version= "0.6.6", git = "https://github.com/agourlay/zip.git", branch = "zip-password-finder" } # dedicated fork
pbkdf2 = "0.12.1" # parallel version did not help the performance
hmac = { version = "0.12.1", features = ["reset"] }
sha1 = "0.10.5"
crossbeam-channel = "0.5.8"
clap = { version = "4.3.9", features = ["cargo"] }
indicatif = "0.17.5"
thiserror = "1.0.40"
num_cpus = "1.15.0"
ahash = "0.8.3"

[profile.test]
opt-level = 3 # needed for fast execution

[dev-dependencies]
criterion = { version = "0.5.1", features = ["html_reports"] }

[profile.bench]
debug = true

[[bench]]
name = "password_generator"
harness = false

[[bench]]
name = "password_reader"
harness = false