[package]
name = "zip-password-finder"
version = "0.5.1"
description = "Find the password of protected ZIP files"
authors = ["Arnaud Gourlay <arnaud.gourlay@gmail.com>"]
license = "Apache-2.0"
readme = "README.md"
categories = ["command-line-utilities", "command-line-interface", "zip", "archive", "password"]
edition = "2021"

[dependencies]
zip = "0.6.3"
crossbeam-channel = "0.5.6"
clap = { version = "4.1.0", features = ["cargo"] }
indicatif = "0.17.3"
thiserror = "1.0.38"
num_cpus = "1.15.0"

[profile.test]
opt-level = 3 # needed for fast execution
