[package]
name = "zip-password-finder"
version = "0.6.1"
description = "Find the password of protected ZIP files"
authors = ["Arnaud Gourlay <arnaud.gourlay@gmail.com>"]
license = "Apache-2.0"
readme = "README.md"
categories = ["command-line-utilities", "command-line-interface", "zip", "archive", "password"]
edition = "2021"

[dependencies]
zip = { version= "0.6.3", git = "https://github.com/agourlay/zip.git", branch = "zip-password-finder" } # dedicated fork
pbkdf2 = "0.11.0" # parallel version did not help the performance
hmac = { version = "0.12.1", features = ["reset"] }
sha1 = "0.10.5"
crossbeam-channel = "0.5.6"
clap = { version = "4.1.4", features = ["cargo"] }
indicatif = "0.17.3"
thiserror = "1.0.38"
num_cpus = "1.15.0"

[profile.test]
opt-level = 3 # needed for fast execution
